{{- $api := .Values.api -}}
{{- $svcPort := $api.service.port -}}
{{- $fullname := include "fuel-explorer.fullname" . }}

{{- if $api.ingress.enabled -}}
{{- if and $api.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey $api.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set $api.ingress.annotations "kubernetes.io/ingress.class" $api.ingress.className}}
  {{- end }}
{{- end }}

{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullname }}-api
  labels:
    {{- include "fuel-explorer.labels" . | nindent 4 }}
    app.kubernetes.io/service: {{ $fullname }}-api
  {{- with $api.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and $api.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $api.ingress.className }}
  {{- end }}
  {{- if $api.ingress.tls }}
  tls:
    {{- range $api.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $api.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullname }}-api
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullname }}-api
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
