name: Build and publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish-image:
    runs-on: warp-ubuntu-latest-x64-4x
    if: |
      (github.event_name == 'release' && github.event.action == 'published') ||
      github.ref == 'refs/heads/main' ||
      (github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name == github.repository) ||
      github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3

      - name: Build and push Fuel Explorer Graphql image
        uses: ./.github/actions/docker-publish
        id: publish
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ghcr.io/fuellabs/fuel-explorer
          dockerfile: deployment/Dockerfile
          context: .
