name: Build and publish Helm Chart

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "helm/fuel-explorer/Chart.yaml"
  pull_request:
    types: [ opened, synchronize ]
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  helm-release:
    name: Build Helm Chart
    runs-on: warp-ubuntu-latest-x64-4x
    if: |
      (github.event_name == 'release' && github.event.action == 'published') ||
      github.ref == 'refs/heads/main' || github.event_name == 'pull_request' ||
      github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Package and Push Charts
        uses: bsord/helm-push@v4.1.0
        with:
          useOCIRegistry: true
          registry-url: oci://ghcr.io/fuellabs/helmcharts
          username: ${{ github.repository_owner }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          chart-folder: ./helm/fuel-explorer
